### ISSUE TITLE
ApiGps doesn't get the time Value

### ISSUE THREAD

**Issue by Erothh** [britzke/rennspur#27]
Error Code: 30000
Call: INSERT INTO TEAM_POSITIONS (LATITUDE, LONGITUDE, TIME, RACES_ID, TEAMS_ID) VALUES (?, ?, ?, ?, ?)
	bind => [52.5328156, 13.139971, null, 1, 2]
Query: InsertObjectQuery(<TeamPosition (id=0, latitude=52.5328156, longitude=13.139971, race=1, team=GER 146)>)] with root cause
ERROR 23502: Column 'TIME'  cannot accept a NULL value.

Sending GPS positions with time works, but why isn't there a time when the backend trys to parse it ? File: ApiGPS.java

**Comment by Num2** [comment]
I already noticed it and i'm working on it.

**Comment by britzke** [comment]
May be the solution could be a custom XmlAdapter as proposed in (http://stackoverflow.com/questions/2519432/jaxb-unmarshal-timestamp_). The date  then should be formatted according [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
Be aware that the format can be different in both directions. Because the javascript parser (needed for the fronted) have to parse it, too.

**Comment by Num2** [comment]
I implemented the suggestions from stackoverflow, the time value is getting parsed now successfully.
I used the following format to test: "2017-01-12 20:40:00".
The issue will stay open until i made some tests to make sure it really works flawlessly.

**Comment by LeoWinterDE** [comment]
Why do you not immediately use ISO standardization with timezone details? Or do we switch to `yyyy-mm-dd hh-mm-ss`?

**Comment by britzke** [comment]
If the date format is transferred without TZ info, it must be ensured that it is in UTC, because javax.sql.Timestamp objects do not have a TZ info (see [Java SE 8 Date and Time](http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html)).
But now with the DateAdapter it is even possible for us to convert a time transferred as a long  into a Timestamp.
The source of this issue has been the incompatibility between the definition of the time transfer format for the GPS component and the the standard JAXB/JAXRS implementation for date/time values.
The javascript Date.now() returns the date/time on the basis of UTC. So on the server side could simply adapt this value to a Timestamp.
